(add-to-list 'load-path (expand-file-name "~/.emacs.d/zoo"))
(require 'zoo-dependencies)
(require 'zoo-rainbow-delimiters)
(require 'zoo-paredit)
(require 'zoo-basics)
(require 'zoo-term)
(require 'zoo-evil)
(require 'zoo-theme)
(require 'zoo-whitespace)
(require 'zoo-ruby)
(require 'zoo-clojure)
(require 'zoo-haskell)
